### PR TITLE
Adding notes from Advances in Speech Recognition

### PR DESCRIPTION
**Pull request by speedoholic**
Advances in Speech Recognition is a short video from WWDC19 but includes some noteworthy announcements that can be useful for developers working with speech recognition.

### CODE REVIEW

**Comment by speedoholic** [comment]
Closing this request since notes were already added by another contributor.

**Comment by Blackjacx** [comment]
Hey there 👋

WWDC20 is knocks on your door. I thought it is a good time to ask if you liked the idea with the session notes repo and if you want it back. Since you even contributed, I would like to use the chance and invite you to give feedback to [my tweet on Twitter](https://twitter.com/Blackjacxxx/status/1273534335904362496). 

By giving feedback and/or retweeting you help to make this concept even more popular and maybe attract Apple's attention so they provide it by theirselves in future 🙃

Thank you so much in advance ✌️

**Comment by speedoholic** [comment]
> Hey there 👋
> 
> WWDC20 is knocks on your door. I thought it is a good time to ask if you liked the idea with the session notes repo and if you want it back. Since you even contributed, I would like to use the chance and invite you to give feedback to [my tweet on Twitter](https://twitter.com/Blackjacxxx/status/1273534335904362496).
> 
> By giving feedback and/or retweeting you help to make this concept even more popular and maybe attract Apple's attention so they provide it by theirselves in future 🙃
> 
> Thank you so much in advance ✌️

Added my comments on Twitter and shared your repo with my connections. Looking forward to contribute.

**Comment by stherold** [comment]
Thanks a lot, this is really good to hear 🙏

**Pull request closed without merging**
