### PR TITLE
Add Session "Get your test results faster"

### PR DESCRIPTION
**Pull request by kanjanaSi**
## Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/Blackjacx/WWDC/blob/master/CONTRIBUTING.md) file.
- [x] I have reviewed my own notes for typos, grammar and consistency (if you're submitting notes for a new session)

## Description
Summary of changes made

### CODE REVIEW

**Comment by kanjanaSi** [comment]
@Blackjacx  please label this pr as hacktoberfest-accepted 😁

**Review by Blackjacx — CHANGES_REQUESTED** [review]
Can you please re-format your the markdown? I think this is not what you expected. The current format of all session notes puts a bullet point even before sub-headers. If you do so you'll see it looks much better. The bulletpoints for each header have then to be indented by 2 spaces :-)

Screen Shot 2020-10-28 at 11 30 11

**Review by Blackjacx — APPROVED** [review]
Thanks a lot, interesting topic 👍

**Comment by Blackjacx** [comment]
As always, feel free to re-tweet 👍 
https://twitter.com/Blackjacxxx/status/1322188436120416257

**Pull request merged**
