### PR TITLE
Auto generate readme

### LINKED ISSUE #58: Pre-fill the README file with all the session video URLs
Replace the stubbed out URLs with the actual URLs that take to the right session.

### PR DESCRIPTION
**Pull request by stherold**
## Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/Blackjacx/WWDC/blob/master/CONTRIBUTING.md) file.
- [x] I have reviewed my own notes for typos, grammar and consistency (if you're submitting notes for a new session)

## Description
The readme is now auto-generated plus the following:
- sessions are now stored in folders as one MD file (`session_number.md`) per session (`2020`for this year)
- files not done yet are pre-populatedd with stubs
- once a PR is merged README.md is re-generated using a GitHub action

### Advantages
- No more manual TOC editing
- No more conflicts
- Clean file structure
- Progress added automatically

- Resolves #58 and #57

### CODE REVIEW

**Comment by atereshkov** [comment]
Uh, no. I mean it's cool you have automated it! I just hope we can handle and merge https://github.com/Blackjacx/WWDC/pull/61 somehow :D

**Comment by Blackjacx** [comment]
@atereshkov No problem, I will do that for you ✌️

**Comment by atereshkov** [comment]
@Blackjacx no worries, I can do that myself after you merge this PR. I'll create new one following the new flow. That should be easier for both of us :) Anyway I'm planning on contributing so I'll understand how to do that in terms of new auto-generated style.

**Comment by stherold** [comment]
Okay thank you so much for your contributions (I plan to merge it today) ✌️ This way I can focus on sessions again :-)

**Comment by Blackjacx** [comment]
Alrighty I have to merge to be able to continue with the sessions and not block other ppl. Thumbs pressed 👍

**Pull request merged**
