### PR TITLE
Pre-fill README with Stubbed Sessions

### PR DESCRIPTION
**Pull request by rogerluan**
@Blackjacx hey again 👋 

I put this together mostly to avoid the merge conflicts we've been facing. If everything is set in place beforehand, there're no more merge conflicts unless 2+ people actually touch the same session notes at the same time. 

I knew you wanted to re-sort them in a specific way so I didn't bother sorting/categorizing them in any specific way - they're just sorted by the order seen here https://developer.apple.com/videos/wwdc2020/

The sooner we put something like this in place, the easier it will be :) right now I just scripted everything and manually replaced the 8 session notes we have. But if we had say 80 notes in already, that'd be way more time consuming haha

Next up would be:
- Tweaking the progress.sh to be able to able to count the progress
- Maybe set up GitHub Actions to automatically update the progress on every PR merged 😄 
- Populating with the actual video links. I wonder how did you do this last year?

As always, happy to help, I can tweak as needed. Cheers!

### CODE REVIEW

**Review by Blackjacx — APPROVED** [review]
Wow thats sooooo cool, thank you so much! I remember that last year this made some of the most effort ^^ One thing maybe, could you please put the watched videos on top instead of distributed in the middle of the page? That would be super nice. It would halp to see the progress at one glance (leveraging the MD list numbers).

🙏

**Comment by Blackjacx** [comment]
> Populating with the actual video links. I wonder how did you do this last year?

This would be super helpful yes. Basically I use the wwdc.io mac app which has a share button from which you get a wwdc.io shortcut link which contains the session number :)

**Comment by rogerluan** [comment]
> > Populating with the actual video links. I wonder how did you do this last year?
> 
> This would be super helpful yes. Basically I use the wwdc.io mac app which has a share button from which you get a wwdc.io shortcut link which contains the session number :)

Gotcha haha. Apple, Y U NO make the video IDs incremental according to the order on the website? 😭 

I'll come up with this list quick enough, but in a separate PR :)

**Comment by rogerluan** [comment]
>One thing maybe, could you please put the watched videos on top instead of distributed in the middle of the page? That would be super nice. It would halp to see the progress at one glance (leveraging the MD list numbers).

I can easily do that, although, it would contribute to the increase of merge conflicts. If multiple people move different sessions to the top of the list, conflicts will arise, while if we keep things as is, it's almost certain that there won't be any conflicts. Let me know your thoughts on this before changing it 🙏

**Comment by Blackjacx** [comment]
Okay I get your point, lets go with it and try that out. Fixing the progress script will do the trick

**Comment by Blackjacx** [comment]
> Maybe set up GitHub Actions to automatically update the progress on every PR merged 😄

Would love to have sth like that! The coolest would be to have a badge on top that executes the progress script and displays its output.

**Comment by rogerluan** [comment]
Hey @Blackjacx I created 3 issues to help track these points that I brought up in the original post ☝️  Just so we don't lose track of it, and then there's more visibility to what we have left to do 🎉 

https://github.com/Blackjacx/WWDC/issues/56
https://github.com/Blackjacx/WWDC/issues/57
https://github.com/Blackjacx/WWDC/issues/58

Whoever gets to them first, wins 😈 hahaha 
Cheers!

**Comment by stherold** [comment]
Hey @rogerluan, thanks for your contributions. Your support is really helpful and motivating ;-) 👍

**Pull request merged**
