### PR TITLE
Session 721 - Combine in Practice

### PR DESCRIPTION
**Pull request by mcichecki**
Notes from Combine in Practice session.

### CODE REVIEW

**Comment by Blackjacx** [comment]
Thanks you made a really good summary 👍

**Comment by Blackjacx** [comment]
Hey there 👋

WWDC20 is knocks on your door. I thought it is a good time to ask if you liked the idea with the session notes repo and if you want it back. Since you even contributed, I would like to use the chance and invite you to give feedback to [my tweet on Twitter](https://twitter.com/Blackjacxxx/status/1273534335904362496). 

By giving feedback and/or retweeting you help to make this concept even more popular and maybe attract Apple's attention so they provide it by theirselves in future 🙃

Thank you so much in advance ✌️

**Comment by mcichecki** [comment]
@Blackjacx I think it's a good idea. You can probably rename this repo to WWDC-19-notes and create a new one for 2020.

**Comment by Blackjacx** [comment]
Hey, thanks for reaching out. I thought about "archiving" the current state on a dedicated branch `WWDC19` and use master for the current year...

**Pull request merged**
