### PR TITLE
[Design Proposal] Expandable Sections

### PR DESCRIPTION
**Pull request by rogerluan**
Hey!

I thought that maybe using expandable sections would make the Table of Content a bit easier to navigate. 
- Easy to expand a section, peek its content and collapse it if you're not interested in reading now;
- You never leave the ToC, so it's no hassle to navigate "back" to it once you're done reading a section.
- We can pre-populate with all the videos so new submissions would just need to "fill the gap"

Let me know your thoughts @Blackjacx 🙌 You can check it in action in https://github.com/rogerluan/WWDC/tree/expandable-proposal

Also, regardless if we decide to go on with this or not, I can pre-populate the remaining sections, so we have better visuals of what's left.
Then we can make `progress.sh` work again (or customize it to work with this new README layout) 🎉 

Anyways, I'm open to suggestions.

Cheers!

### CODE REVIEW

**Comment by Blackjacx** [comment]
Thanks a lot for this idea 🙏

This is a nice approach to get rid of the ToC but actually I like it that way it is. With the collapsible sections I cannot generate links anymore to the different sections (try this: https://github.com/rogerluan/WWDC/tree/expandable-proposal#explore-arkit-4 - it doesn't take you to the section anymore). Also we loose the automatic numbering by markdown which is key when it comes to re-ordering the sections, what I usually do at some point. I leave your PR open and think a little bit more about it 👍

**Comment by rogerluan** [comment]
Sure, not a problem! Your comments are valid, and it's mostly a matter of personal preference. Either way works for me :)

**Comment by rogerluan** [comment]
Can we close this PR @Blackjacx ? I don't think we'll move forward with this one anymore

**Comment by Blackjacx** [comment]
Yes Sir, I actually wanted to ask the same ✌️

**Pull request closed without merging**
