### PR TITLE
added notes for Designing Great ML Experiences talk

### PR DESCRIPTION
**Pull request by sidharthshah**
I've added notes for a Session

### CODE REVIEW

**Comment by Blackjacx** [comment]
Can you put your change below the last addition please? This way we can see how much is missing more easy.

**Comment by sidharthshah** [comment]
Sorry, my bad didn't get what you're suggesting. Do you mean

A) I need to add changes below the contents of the last commit? or
B) I need to give context to the commit as so which section does it belong to?

**Comment by Blackjacx** [comment]
Oh sorry, no I mean 

Can you please move the session you added right below the last session that has been added?

But I can do it quickly too when I have time reviewing your PR (this evening I think). 👍

**Comment by sidharthshah** [comment]
@Blackjacx, when you have time please do it. Because I believe I've updated fist "todo" session {right below the one that is already curated}. Also would be more than happy to help if you need help with something as a priority.

**Comment by Blackjacx** [comment]
Oh wow sorry, didn't see it. Yes you are right. Nothing to do anymore. Sorry fr the hassle 😅

**Comment by sidharthshah** [comment]
👍 its cool! I appreciate your work on this repo. Keep it up!

**Comment by Blackjacx** [comment]
Thanks so much for your addition. I streamlines it a little bit. But otherwise very cool 👍

**Comment by Blackjacx** [comment]
Hey there 👋

WWDC20 is knocks on your door. I thought it is a good time to ask if you liked the idea with the session notes repo and if you want it back. Since you even contributed, I would like to use the chance and invite you to give feedback to [my tweet on Twitter](https://twitter.com/Blackjacxxx/status/1273534335904362496). 

By giving feedback and/or retweeting you help to make this concept even more popular and maybe attract Apple's attention so they provide it by theirselves in future 🙃

Thank you so much in advance ✌️

**Pull request merged**
